Feature attr override
inacademia-development/svs pull request #31
Opened 2020-09-16 11:03 UTC by mrvanes

This implements the conditional attribute override possibility.

2020-09-18 22:50 UTC, c00kiemon5ter requested changes
Based on the assumptions I describe, I think we can simplify this. I could be thinking this wrongly - lets discuss.

2020-09-18 22:50 UTC, c00kiemon5ter commented on example/attribute_override.yaml.example
> +      # and values 'urn:oid:foo:employee' on affiliation values employee
```suggestion
      # and values 'urn:oid:foo:employee' on affiliation values 'employee'
```

2020-09-18 22:50 UTC, c00kiemon5ter commented on example/attribute_override.yaml.example
> +        'urn:oid:foo:employee': [affiliation, 'employee']
```suggestion
        'urn:oid:foo:student': ['affiliation', 'student']
        'urn:oid:foo:employee': ['affiliation', 'employee']
```

2020-09-18 22:50 UTC, c00kiemon5ter commented on example/attribute_override.yaml.example
> +        'urn:oid:bar:member': [affiliation, 'student']
```suggestion
        'urn:oid:bar:member': ['affiliation', 'student']
```

2020-09-18 22:50 UTC, c00kiemon5ter commented on example/attribute_override.yaml.example
> +        'urn:oid:foo:student': [affiliation, 'student']
Will "entitlement" and "affiliation" ever be something different?

From what I understand, what we want to do is set the affiliation based on an entitlement value. We map entitlements to affiliations. I think we can simplify this - here's how I think of the configuration, and the code follows:

```yaml
module: svs.attribute_override.AttributeOverride
name: AttributeOverride
config:

  # the internal attribute name for entitlement
  entitlement_attribute: entitlement
  # the internal attribute name for affiliation
  affiliation_attribute: affiliation

  # mapping entitlement to affiliation for each provider
  entitlement_to_affiliation:
    urn:mace:idp.foo.one:
      urn:oid:foo:student: student
      urn:oid:foo:fellow: student
      urn:oid:foo:employee: employee
    urn:mace:idp.foo.two:
      urn:oid:foo:member: student
```

2020-09-18 22:50 UTC, c00kiemon5ter commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
with the above in mind, we can write this like:

```python
...
from satosa.exception import SATOSAError


class AttributeOverrideError(SATOSAError):
    """Generic error."""


class AttributeOverride(ResponseMicroService):
    """
    Metadata info extracting micro_service
    """

    def __init__(self, config, internal_attributes, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.entitlement_attribute = config.get('entitlement_attribute')
        self.affiliation_attribute = config.get('affiliation_attribute')
        self.entitlement_to_affiliation = config.get('entitlement_to_affiliation', {})
        if not self.entitlement_attribute or not self.affiliation_attribute:
            raise AttributeOverrideError("Invalid configuration: entitlement_attribute and affiliation_attribute are required")

    def process(self, context, data):
        ra = context.state['metadata']['ra']
        entitlement_to_affiliation = self.entitlement_to_affiliation.get(ra, {})
        affiliations_from_entitlements = [
            entitlement_to_affiliation.get(entitlement) or entitlement
            for entitlement in data.attributes.get(self.entitlement_attribute, [])
        ]
        affiliations_merged = data.attributes.get(self.affiliation_attribute, []).extend(affiliations_from_entitlements)
        data.attributes[self.affiliation_attribute] = affiliations_merged

        return super().process(context, data)
```

* get the configuration options and validate them
* get the right mapping based on "ra"
* collect the new affiliations based on the user's entitlements
* merge the new affiliations with the old
* replace the old attribute value

2020-09-19 08:14 UTC, mrvanes commented on example/attribute_override.yaml.example
> +        'urn:oid:foo:student': [affiliation, 'student']
Yes, Niels' original request was to make this as generic as possible, hence the awkward configuration... I do not see any other purpose (at the moment) though.

2020-09-24 06:49 UTC, mrvanes commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
Rejected

2020-09-24 18:14 UTC, c00kiemon5ter requested changes
Ideas for improvements. How pressed are we to deliver this? If we have time we can work on it more.

2020-09-24 18:14 UTC, c00kiemon5ter commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
In general, I prefer a model where in one step we collect the data we need, and then in another step we mutate existing values. Same goes for logging - the computation of a value and logging should be separate. Logging should be a separate step and should be reporting the internal state, not an action.

I would think of the steps as:

- for each internal attribute from which we convert values, check if it contains the values that the configuration defines they need to be converted, convert them and map them to the internal attribute that they will be assigned to.

The result of this is a new structure that maps the internal attributes that will be assigned new values, to the additional values that it will get. This structure can be logged as is.

- for each internal attribute to which we will assign new values, if we have new values for it, merge the values with the existing values and make sure they are unique and map them again to the internal attribute to which they will be assigned.

The result is again a structure that maps the internal attributes that will be assigned new values, to those new values. This structure can be logged as is.

- finally, mutate: assign the values to the internal attributes on the `internal_response` object.

The result is that we have separated processing, from logging and mutating.

2020-09-24 20:03 UTC, mrvanes commented on example/attribute_override.yaml.example
> +        'urn:oid:foo:member': ['affiliation', 'student']
I have thought about the dict representation and found it way to bulky to do any good, I eventually decided the list representation was both sensical and concise,  but it needs to comments to explain how to read the conf, which should be no problem if it's left there?

2020-09-24 20:04 UTC, mrvanes commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
There is no "additional values", all original values need to be replaced:
https://wiki.geant.org/display/INACTS/Allow+certain+IDPs+to+send+affiliation+with+specific+entitlement+values

2020-09-24 21:10 UTC, c00kiemon5ter commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
in the case of mapping entitlement values to affiliation values, and assuming that the IdP has sent some affiliation values back; if we discard the existing affiliation values (thus no additional values) then we just have one less step. The logic is still the same.

2020-09-24 21:23 UTC, c00kiemon5ter commented on example/attribute_override.yaml.example
> +        'urn:oid:foo:member': ['affiliation', 'student']
We have something that works; does it provide real value to change it? It does only if we ever need to change this in the future. If the answer is only up to me, I would change it. 

Right now, I can do `'urn:oid:foo:student': ['affiliation', 'student', 'foo', 'bar']` which does not make sense. I would eliminate this possibility. Right now, if I want to map multiple values to 'student' I have to repeat the structure `'urn:oid:foo:student': ['affiliation', 'student'], 'urn:oid:foo:pupil': ['affiliation', 'student']`. Right now, the code picks up the first and second item in a list and does stuff with those; I consider those to be _magic values_, and I would change the configuration to make them be something.

At the moment all micro-services have a static configuration, but what we maybe doing in the future, is providing the configuration dynamically. In that case the configuration would live in a database defined by a schema. At that point, doing special things with items in a list becomes problematic. But if the configuration is fine, when we get to transition to a database what changes is the just the initialization. The logic of the computation is the same. I find this to be a good thing.

2020-10-21 10:19 UTC, mrvanes commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
I suggest we merge and leave it up to Paulo and us to decide whether we configure this micro_service as it is in prd after release?

2020-10-21 10:24 UTC, c00kiemon5ter approved these changes

2020-10-21 10:24 UTC, c00kiemon5ter commented on src/svs/attribute_override.py
> +                        internal_response.attributes[dst_a].append(dst_v)
Let's do it ;)

2020-10-21 10:30 UTC, merged