Add idp_hint asserting micro service
inacademia-development/svs pull request #32
Opened 2020-09-17 12:22 UTC by mrvanes

This PR needs additional configuration:
An idp_assert.yaml config file:
```
module: svs.assert_hint.AssertHint
name: AssertHint
config:
    internal_attribute: 'idp_used'
```
And an extra plugin line in satosa proxy_conf.yaml:
```
  ...
  - 'plugins/assert_hint.yaml'
  ...
```
The cdb.json RP configuration to be extended with idp_hint as allowed claim:
```
  "rp": {
    "allowed_claims": [
      "domain",
      "country",
      "institution",
      "idp_hint"
    ],
    ...
```
And internal_attributes.yaml to be extended with an oidc idp_hint claim, based on the internal attribute configured in the assert_idp.yaml configuration file:
```
  ...
  idp_used:
    openid: [idp_hint]
```

2020-09-18 23:22 UTC, c00kiemon5ter requested changes
A suggestion to avoid caring where the idp_hint came from.

2020-09-18 23:22 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +                idp_hint_key = claims['id_token']['idp_hint']['value']
instead of checking the query-params/POST-body-claims, I think the idp_hint should be stored in the context-state/cookie when processing the request. We have already looked into the params and the request body during that time; we should not be doing it again. When we process the response and get to this point we can retrieve this from the state without caring if it was a query param or something else.

2020-09-18 23:22 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +        if idp_hint_key != None:
```suggestion
        if idp_hint_key is not None:
```

2020-09-18 23:22 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +            # This from inacademia-hinting code
I think it would be best to wrap the common part in a function, so that it's easier to sync and harder to mix it with other concerns, if future changes are needed.

2020-09-19 08:23 UTC, mrvanes commented on src/svs/assert_hint.py
> +                idp_hint_key = claims['id_token']['idp_hint']['value']
I was trying to prevent continuously increasing state bloat by replacing it with code duplication... when will the state size break agents I wonder? Is there a limit on cookie size? It feels like careless capacity management to put everything on the state.

2020-09-19 23:18 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +                idp_hint_key = claims['id_token']['idp_hint']['value']
It actually is part of the state though. There is nothing to guarantee that the response will not have been stripped out of the query params you expect (`idp_hint` in this case). The only point that you actually know that the idp_hint was there, is when you process the request. At that point you need to extract the information you need to keep, and put it into the state.
I am not sure what `context.state['InAcademia']` holds. If the complete request is there then you are probably already holding more information than you need.

The point of my comment though was different. Right now, you are coupling the request format to a concept that you need to get hold of - the idp_hint. The microservice should not need to know anything about the network, query params, request bodies, etc - it only cares about the idp_hint. The processing that happens before the microservice should have already established a way to get this information. Whether this information came from a query param, a request body, a database or anywhere else should be irrelevant here.

2020-09-20 17:52 UTC, mrvanes commented on src/svs/assert_hint.py
> +                idp_hint_key = claims['id_token']['idp_hint']['value']
Yes, it's already part of the state, but it would add the same information in another format, hence bloat. But I agree that it may be better for a front-end to figure out the hint and for the micro_service to hand on it independant of the way the information was conceived. I will implement the state version. And yes, maybe we should trim down context.state['InAcademia'] somewhat and store only what we need later on!

2020-09-21 07:39 UTC, mrvanes commented on src/svs/assert_hint.py
> +            # This from inacademia-hinting code
I don't see the common part?

2020-09-21 08:21 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +            # This from inacademia-hinting code
by "common part" I meant the "inacademia-hinting code". I am guessing the comment refers to just the line below that hashes the issuer using SHA1. Putting it in a function named appropriately will make it clear that it should be changed without taking into account the inacademia-hinting code. I would go with something like:

```python
def inacademia_hinting_hash(data):
    """
    Hash data the same way this is done in the inacademia-hinting code.

    This code should not be changed on its own - if needed, it should be
    changed in-sync with the inacademia-hinting code.
    """
    raw = data.encode("utf-8") if isinstance(data, str) else data
    hash = hashlib.sha1(raw).hexdigest()
    return hash
```

2020-09-21 08:29 UTC, mrvanes commented on src/svs/assert_hint.py
> +            # This from inacademia-hinting code
And would that function preferably live in assert_hint.py or somewhere more generic in utils?

2020-09-21 08:42 UTC, c00kiemon5ter commented on src/svs/assert_hint.py
> +            # This from inacademia-hinting code
yep, on the same file. The point is to make it explicit that this should not be changed, and it marks that it depends on the way some other part of the service works.

2020-09-21 13:06 UTC, c00kiemon5ter approved these changes

2020-09-25 08:58 UTC, merged