RP provides unsupported claim in the authorization request
inacademia-development/svs pull request #49
Opened 2020-12-22 21:02 UTC by smalihaider

- [X ] I updated the CHANGELOG.md

2020-12-28 21:27 UTC, c00kiemon5ter requested changes
I think we can simplify `_get_approved_attributes`

2020-12-28 21:27 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +def claims_request_is_valid(provider, authentication_request):
- before, we were validating the claims at the beginning of `_handle_authn_request` through `self.provider.parse_authentication_request(request)`
- now, we are filtering the claims at the end of `_handle_authn_request`

The check we had in `claims_request_is_valid_for_client` was making sure that all claims requested by the id_token were allowed by the client configuration. Per the specification this is not needed. Since the check is not looking into the client configuration anymore, we also remove the `_for_client` part from the function name.

2020-12-28 21:27 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +    def _get_approved_attributes(self, provider_supported_claims, authn_req):
- before, `_get_approved_attributes` was filtering the claims (both from scope or explicitly requested) by the supported claims of the provider
- now, `_get_approved_attributes` is _additionally_ filtering by the allowed claims of the client

I think we can simplify `_get_approved_attributes` by doing exactly the above. Let the function filter as it was doing before, and filter the result further by the allowed claims of the client.

```python
def _get_approved_attributes(self, provider_supported_claims, authn_req):
    claims_filtered_by_provider_supported = super()._get_approved_attributes(provider_supported_claims, authn_req)
    claims_allowed_for_client = self.provider.clients[authn_req['client_id']].get('allowed_claims', {})
    approved_claims = claims_filtered_by_provider_supported.intersection(claims_allowed_for_client)
    return approved_claims
```

---

The end result is that the claims that are not supported by the provider configuration (that part was already there) and not allowed by the client configuration (what was added) are filtered out -- they are ignored; which is valid behaviour by the spec.

2020-12-28 21:53 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +    def _get_approved_attributes(self, provider_supported_claims, authn_req):
Yes, I agree. Let me do this change.

2020-12-28 21:53 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +def claims_request_is_valid(provider, authentication_request):
Yes, but I have already removed the `_for_client` part from the `claims_request_is_valid_for_client` function name? I didn't understand what change are you proposing here?

2020-12-28 22:20 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +def claims_request_is_valid(provider, authentication_request):
I'm not proposing a change. I'm explaining what is happening for me and other that might read this ;)

2020-12-29 12:51 UTC, mrvanes commented on src/svs/inacademia_frontend.py
> +from oic.oic import scope2claims
Don't forget to remove this import when you implement @c00kiemon5ter's version of ```_get_approved_attributes```

2020-12-29 17:51 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +def claims_request_is_valid(provider, authentication_request):
oh okay, then I must say thank you for commenting on this :)

2020-12-29 20:32 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +    def _get_approved_attributes(self, provider_supported_claims, authn_req):
Changes done.

2020-12-30 00:26 UTC, c00kiemon5ter approved these changes

2021-01-03 10:17 UTC, merged