Added error handling: RP requests claims in invalid JSON format in the authorization request
inacademia-development/svs pull request #50
Opened 2020-12-26 18:29 UTC by smalihaider

- [ X] I updated the CHANGELOG.md

2020-12-28 22:14 UTC, c00kiemon5ter requested changes

2020-12-28 22:14 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +    @staticmethod
is there a reason we mark this as a static method?

2020-12-28 22:14 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +                                                        ERROR_DESC].format(param))
the only difference here is whether state is included; we can rewrite this to reflect that

```python
state_param = {"state": request['state']} if request['state'] else {}
error_description = ErrorDescription.REQUEST_PARAM_INVALID_FORMAT[ERROR_DESC].format(param)
error_resp = AuthorizationErrorResponse(
    error="invalid_request", error_description=error_description, **state_param,
)
```

2020-12-29 13:32 UTC, mrvanes commented on src/svs/inacademia_frontend.py
> +                                                        ERROR_DESC].format(param))
Shouldn't
```if request['state']```
read
```if request.get('state')```?

2020-12-29 18:47 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +                    raise Exception('parameter is a valid json but does not contain a key value pair.')
But in [OIDC docs - additional claims section ](https://openid.net/specs/openid-connect-core-1_0.html#AdditionalClaims), claims parameter in addition to being a valid JSON, should also conform with the specification that the top-level members of the Claims request JSON object can only be `userinfo` or `id_token`.  And this check has exactly been added to reject claims parameter value of string like "abc".

2020-12-29 18:53 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +        except Exception as exception:
Yes, at first I used JSONDecodeError here, but then for the case where we would like to reject a JSON string like "abc", I added, "raise Exception". So I replaced JSONDecodeError with Exception to catch that general Exception. But let me improve this a bit taking inspiration from the _validate_authn_request_format code you listed in your other comment.

2020-12-29 19:21 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +                    raise Exception('parameter is a valid json but does not contain a key value pair.')
I'm not sure I understand this. 

At this point, `claims` is the value of the claims query param. We do not know if this value is valid JSON, a string, a number or anything else. We first need to verify that it is a JSON object. Verifying it is a JSON object is not enough. We also need to make sure we got a Mapping (and not a JSON array, for example).

I don't see why we need to look inside the value _before_ parsing it. After we've parsed the value and we know we have a Mapping, and this gives us the ability to work with that value in a safe manner. Then, we can check that its keys are `userinfo` and/or `id_token`. 

These are _not the only members_ allowed. Even those members are optional.
From [section "5.5.  Requesting Claims using the "claims" Request Parameter"](https://openid.net/specs/openid-connect-core-1_0.html#ClaimsParameter)
> The top-level members of the Claims request JSON object are:
>
> - userinfo: OPTIONAL [...]
> - id_token: OPTIONAL [...]
>
> Other members MAY be present. Any members used that are not understood MUST be ignored.

We do not need to check for those keys (members). When we use that structure, we request the claims for those members explicitly, for example this is what was done in [`_get_approved_attributes` in #49](https://github.com/inacademia-development/svs/pull/49/commits/70bb9fd6a244e4ed380a5a16b0c54f2a8e67744e#diff-cdfe735d253268b914a4967c9c55b9b7b35fed9b00d5271170f5355807c5b484R138-R140)

2020-12-29 19:32 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +        authn_request_format_error = self._validate_authn_request_format(context.request)
The problem is that the built-in validation chain uses `claims_request_deser` in oic.oic.message.py which triggers first and it assumes that the claims request parameter is always going to be valid JSON and hence result in json.decoder.JSONDecodeError. This is exactly the issue we are trying to solve here.

So we must plug our implementation such that the claims format validation is triggered before parse_authentication_request is called. And that is why I think we should validate this before `super()._handle_authn_request(context)` is called in `handle_authn_request`.

2020-12-29 19:42 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +        authn_request_format_error = self._validate_authn_request_format(context.request)
OK, let's do that ;)

2020-12-29 20:28 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +            claims = request['claims']
Agreed. Change done.

2020-12-29 20:29 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +        return None
I have made some changes in the method taking inspiration from the code snippet you shared.

2020-12-29 20:31 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +    @staticmethod
Well, the only reason to make it static was that this method is not relying on the state of InAcademiaFrontend object. It is simply a utility method to return the SeeOther response based on the specified parameters.

2020-12-29 20:31 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +                                                        ERROR_DESC].format(param))
Changes done

2020-12-29 21:04 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +                    raise Exception('parameter is a valid json but does not contain a key value pair.')
Yes, you are right. I have changed the code as per your suggestions. Does this look fine to you now?

2020-12-30 11:19 UTC, c00kiemon5ter requested changes

2020-12-30 11:19 UTC, c00kiemon5ter commented on src/svs/inacademia_frontend.py
> +        if claims:
While the method is correct, I do not think that this is right. We should not specialize the main purpose of this method. We should branch out to handle the side-cases. The main business of this method is to validate a value. If there is no value we stop early; it is not the other way around.

This hints to me that we're doing something else wrong, because we should not need to return early. We are passing in the `request` but we're only interested in its `claims` member. We should be passing in just that.

---

Additionally, this method is called `_validate_[...]`. It should either return or raise an exception. If it was called `_is_valid_[...]` it should either return `True` or `False`. But, this method is doing neither; it is doing its own thing - namely, it is returning an error, which is then returned further up by the caller.

I think this is wrong. It should raise the error with the context that it has. The caller should catch the error and handle it as it needs.

---

Think these two points, I think this should be restructured.

2020-12-31 19:21 UTC, smalihaider commented on src/svs/inacademia_frontend.py
> +        if claims:
Thanks, @c00kiemon5ter for your thoughtful review. I have made the suggested changes but I must mention, that initially, I implemented this method with the viewpoint that this method `_validate_authn_request` will be expanded to validate other request constraints as well which I would be working on in the coming days. For example: if client_id or redirect_uri is invalid we need to show InAcademia error page instead of redirecting to invalid RP or invalid client, also if client_id or redirect_uri do not match with the `cdb.json` data, in that case as well we need to redirect to InAcademia error page. (Error 1 - 4 ) 

But anyway, I think you are right, for now, let's concentrate on the claims.

2021-01-01 10:04 UTC, c00kiemon5ter approved these changes

2021-01-03 10:21 UTC, merged